MASS = "star_mass"
YINI = "Yinit"
ZINI = "Zinit"
AMLT = "amlt"
FOVC = "fov_core"
FOVS = "fov_shell"

AGE  = "star_age"
RAD  = "radius"
TEFF = "Teff"
XCEN = "center_h1"
LLHE = "log_LHe"
LLNB = "log_Lnuc"
DNUF = "Dnu_freq_o"
EPSP = "eps_o"
DPIG = "delta_Pg"

FREQ = "mode_freq_o"
